### ISSUE TITLE
Error trying to execute SimpleEchoClient

### ISSUE THREAD

**Issue by antolinos95** [h2r/java_rosbridge#4]
Hi!
I get the next exception when I execute SimpleEchoClient or RosTest:

> Exception in thread "main" java.lang.NullPointerException
>   at org.eclipse.jetty.websocket.common.extensions.AbstractExtension.getName(AbstractExtension.java:90)
>   at org.eclipse.jetty.websocket.api.extensions.ExtensionFactory.<init>(ExtensionFactory.java:37)
>   at org.eclipse.jetty.websocket.common.extensions.WebSocketExtensionFactory.<init>(WebSocketExtensionFactory.java:40)
>   at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:85)
>   at org.eclipse.jetty.websocket.client.WebSocketClient.<init>(WebSocketClient.java:78)
>   at tests.SimpleEchoClient.main(SimpleEchoClient.java:18)

Thank you!

**Comment by stefie10** [comment]
I'm going to guess it's something to do with Jetty not having all the 
libraries that it needs...  It's trying to load an extension and 
failing.  Is Jetty installed correctly?  Your classpath set up?  Have 
you tried looking on Jetty forums?

**Comment by antolinos95** [comment]
It was a weird conflict between different versions of Jetty, now it's solved.
Thank you! :smile:
